# Generated by Django 3.1 on 2022-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acount_id', models.CharField(max_length=255, verbose_name='アカウントID')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
            ],
            options={
                'verbose_name': 'アカウント一覧',
                'verbose_name_plural': 'アカウント一覧',
                'db_table': 'acount',
            },
        ),
    ]
